name: Test init-template script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  init-template:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check init-template.sh
      run: |
        ./init-template.sh my-test_app

    - name: build
      run: |
        nix build -L
        ./result/bin/mytestapp --help
